version: '3'

services:
  web:
    build: .
    platform: linux/amd64   # Moved out of build
    ports:
      - "8000:4000"
    depends_on:
      - database
    environment:
      NODE_ENV: production

  database:
    image: mongo:3.2
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: